version: '3.8'

services:
  db:
    container_name: df-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  amqp:
    container_name: df-rabbitmq
    image: rabbitmq:3.13.6-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  php:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: df-app
    restart: unless-stopped
    tty: true
    volumes:
      - ./app:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  worker:
    container_name: df-worker
    build:
      context: ./worker-importer
      dockerfile: Dockerfile
    depends_on:
      - db
      - amqp
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: df-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
