version: '3.8'

services:
  nginx:
    container_name: df-nginx
    image: nginx:latest
    volumes:
      - ./docker/settings/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/settings/nginx/conf.d:/etc/nginx/conf.d
      - ./app:/app
    ports:
      - "80:80"

  php:
    container_name: df-php
    build:
      context: ./docker/builds/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./docker/settings/php/.env:/app/.env
      - ./docker/storage/database/database.sqlite:/app/database/database.sqlite
      - ./docker/settings/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/settings/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - "9000:9000"
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    container_name: df-rabbitmq
    image: rabbitmq:3.13.6-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "dfadmin"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: df-redis
    image: redis:latest
    ports:
      - "6379:6379"